### 회원가입
POST localhost:8080/api/member/join
Content-Type: application/json

{
  "email" : "wanted@google.com",
  "password" : "wanted1234"
}


### 회원 로그인
POST localhost:8080/api/member/login
Content-Type: application/json

{
  "email" : "wanted@google.com",
  "password" : "wanted1234"
}
